### ISSUE TITLE
"contentServer.open : boolean | object"  mismatch type declaration

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#10] opened 2020-08-04 10:43 UTC
When `reboost.js` lies in the root dir the `open: true` option is accepted without complain.

But when `reboost.js` lies in a dir like `./.config/reboost/` then `open: true` option is NOT accepted. See photo below.

![reboost-1](https://user-images.githubusercontent.com/26875662/89283733-eb7ec100-d64d-11ea-9cb8-995a4751f135.png)

**Comment by sarsamurmu** [comment] 2020-08-04 11:19
I think the problem is with the Typescript declaration files. Don't worry, I will fix it soon.

**Comment by sarsamurmu** [comment] 2020-08-04 13:36
Fixed in the latest version. Just update it.

**Closed as completed by sarsamurmu** 2020-08-04 13:36 UTC
